/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecto2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.StringTokenizer;

/**
 *
 * @author alex
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    Arbol arbol;
    public main() {
        initComponents();
        this.setLocationRelativeTo(this);
        try{
            String s1;
            String s2;
            String texto="";
            int tabs=10;
            boolean continuar=true;
            Nodo temp=null;
            int hijo=0,hijo2=0,hijo3=0;
                   
            BufferedReader br = new BufferedReader (new FileReader("arbol.txt"));
              
            while((s1 = br.readLine()) != null){
                System.out.println(s1);
                while (continuar==true) {                    
                    for (int i = tabs; i > 0; i--) {
                        texto+="\t";
                    }
                    if(s1.contains(texto)){
                        continuar=false;
                        
                        if(tabs==0){
                            arbol = new Arbol(new Nodo(null, s1));
                            System.out.println((String)arbol.raiz.label);
                        }
                         if(tabs==1){
                            temp=arbol.raiz;
                            arbol.raiz.agregar_nodo(new Nodo(temp, s1));
                            hijo++;
                        }
                        if (tabs==2) {
                            ((Nodo)arbol.raiz.hijos.get(hijo-1)).agregar_nodo(new Nodo(((Nodo)arbol.raiz.hijos.get(hijo-1)).padre, s1)); 
                            hijo2++;
                        }
                        if (tabs==3) {
                           ((Nodo)((Nodo)arbol.raiz.hijos.get(hijo-1)).hijos.get(hijo2-1)).agregar_nodo(new Nodo(((Nodo)((Nodo)arbol.raiz.hijos.get(hijo-1)).hijos.get(hijo2-1)).padre, s1));
                           hijo3++;
                        }
                    }
                    tabs--;
                    texto="";
                }
                
                continuar=true;
                tabs=10;
            }
        
            br.close();
        }catch (Exception e){ //Catch de excepciones
            System.err.println("Ocurrio un error: " + e.getMessage());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrar_arbol = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol_t = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        arbol_t.setColumns(20);
        arbol_t.setRows(5);
        jScrollPane1.setViewportView(arbol_t);

        jLabel2.setText("Arbol");

        javax.swing.GroupLayout mostrar_arbolLayout = new javax.swing.GroupLayout(mostrar_arbol.getContentPane());
        mostrar_arbol.getContentPane().setLayout(mostrar_arbolLayout);
        mostrar_arbolLayout.setHorizontalGroup(
            mostrar_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrar_arbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(mostrar_arbolLayout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel2)
                .addContainerGap(510, Short.MAX_VALUE))
        );
        mostrar_arbolLayout.setVerticalGroup(
            mostrar_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrar_arbolLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Projecto 2");

        jButton1.setText("Mirar Arbol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton1)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tex="";
        tex+=((String)arbol.raiz.label);
        for (int i = 0; i < arbol.raiz.hijos.size(); i++) {
            tex+="\n";
            tex+=("\t"+(String)((Nodo)arbol.raiz.hijos.get(i)).label);
            for (int j = 0; j < ((Nodo)arbol.raiz.hijos.get(i)).hijos.size(); j++) {
                tex+="\n";
                tex+=("\t"+(String)((Nodo)((Nodo)arbol.raiz.hijos.get(i)).hijos.get(j)).label);
                for (int w = 0; w < ((Nodo)((Nodo)arbol.raiz.hijos.get(i)).hijos.get(j)).hijos.size(); w++) {
                    tex+="\n";
                    tex+=("\t"+(String)((Nodo)((Nodo)((Nodo)arbol.raiz.hijos.get(i)).hijos.get(j)).hijos.get(w)).label);
                }
            }
        }
        arbol_t.setText(tex);
        mostrar_arbol.setSize(1000, 700);
        mostrar_arbol.setLocationRelativeTo(this);
        mostrar_arbol.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arbol_t;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog mostrar_arbol;
    // End of variables declaration//GEN-END:variables
}
